[package]
name = "omniverlay_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
dirs = "5.0.1"
env_logger = "0.11.5"
log = "0.4.22"
once_cell = "1.19.0"
serde = "1.0.204"
serde_json = "1.0.122"
tauri = "1.7.1"
thiserror = "1.0.63"
tokio = "1.39.2"
