[package]
name = "performance"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
omniverlay_core = { path = "../../core" }
serde = "1.0.204"
serde_json = "1.0.122"
sysinfo = "0.31.2"
tauri = "1.7.1"
tokio = "1.39.2"
